services:
  haproxy:
    image: my-haproxy
    networks:
      - haproxy_network1
    ports:
      - '8000:5000'
  fi1: 
    image: python-server1
    ports:
      - '5000:5000'
  fi2: 
    image: python-server-fi2
    ports:
      - '4040:5000'
  de1: 
    image: python-server2
    ports:
      - '5005:5000'

networks:
  haproxy_network1:
    name: haproxy_network1
    external: true