services:
  redis: 
    image: redislabs/redismod
    ports:
      - '6379:6379' 
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
  web:
    build: .
    ports:
    - "9000:5000"
    volumes:
    - ./:/src
    depends_on:
    - redis